CREATE TABLE USERS_BKS (
NOME VARCHAR(20),
COGNOME VARCHAR(20),
EMAIL VARCHAR(100),
PASSWORD VARCHAR(20),
ID INT PRIMARY KEY,
PROFILE INT );
-----------------------------------------------------
CREATE TABLE USER_PROFILE_BKS(
ID INT PRIMARY KEY,
NOME VARCHAR(30)
);
CREATE TABLE PROFILE_FUNCTION_MENU_BKS(
ID_PROFILE INT,
ID_FUNCTION INT
);

-----------------------------------------------------
CREATE TABLE FUNCTION_BKS(
ID INT PRIMARY KEY,
NOME VARCHAR(40),
URL_FUNCTION VARCHAR(200)
);
-----------------------------------------------------
CREATE TABLE LIBRO_BKS(
ID INT PRIMARY KEY,
TITOLO VARCHAR(1000),
DESCRIZIONE VARCHAR(200),
DATA_PUBLICAZIONE DATE,
COPERTINA BLOB,
PREZZO FLOAT, 
GENERE_ID INT,
EDITORE_ID INT,
AUTORE_ID INT

);
-----------------------------------------------------
CREATE TABLE GENERE_BKS(
ID INT,
TIPOLOGIA VARCHAR(50)
);
-----------------------------------------------------
CREATE TABLE AUTORE_BKS(
ID INT PRIMARY KEY,
NOME VARCHAR(40),
COGNOME VARCHAR(40),
DESCRIZIONE VARCHAR(200)

);
-----------------------------------------------------
CREATE TABLE EDITORE_BKS(
ID INT PRIMARY KEY,
NOME  VARCHAR(100)
) ;





SELECT LIBRO_BKS.* FROM LIBRO_BKS ;

DELETE TABLE USERS_BOOKSHOP;