DROP TABLE BKS_USERS;
--DROP TABLE USERS_BOOKSHOP;
DROP TABLE BKS_USER_PROFILE;
DROP TABLE BKS_PROFILE_FUNCTION_MENU;
DROP TABLE BKS_FUNCTION;
DROP TABLE BKS_LIBRO;
DROP TABLE BKS_GENERE;
DROP TABLE BKS_AUTORE;
DROP TABLE BKS_EDITORE;

--DROP TABLE FIRSTTABLE;
--DROP TABLE SECONDTABLE;
SELECT * FROM FIRSTTABLE;