DROP TABLE USERS_BKS;
--DROP TABLE USERS_BOOKSHOP;
DROP TABLE USER_PROFILE_BKS;
DROP TABLE PROFILE_FUNCTION_MENU_BKS;
DROP TABLE FUNCTION_BKS;
DROP TABLE LIBRO_BKS;
DROP TABLE GENERE_BKS;
DROP TABLE AUTORE_BKS;
DROP TABLE EDITORE_BKS;

--DROP TABLE FIRSTTABLE;
--DROP TABLE SECONDTABLE;
SELECT * FROM FIRSTTABLE;