
-------------------------------------COMNTROL QUERY--------------------------------------------------------

SELECT * FROM LIBRO_BKS;
SELECT * FROM AUTORE_BKS;
SELECT * FROM GENERE_BKS;
SELECT * FROM EDITORE_BKS;
SELECT P.ID,U.EMAIL,U.PASSWORD,P.NOME FROM USERS_BKS AS U,USER_PROFILE_BKS AS P WHERE P.ID=U.PROFILE;
SELECT * FROM USER_PROFILE_BKS;



-------------------------DELETE BEFORE INSERT-----------------------------------
DELETE FROM LIBRO_BKS WHERE ID =1000;
DELETE FROM LIBRO_BKS WHERE ID =1010;
DELETE FROM LIBRO_BKS WHERE ID =1020;
DELETE FROM LIBRO_BKS WHERE ID =1030;
DELETE FROM LIBRO_BKS WHERE ID =1040;
DELETE FROM LIBRO_BKS WHERE ID =1050;
------------------------------INSERT---LIBRO_BKS-------------------------------
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1000,'IL CICLOPE','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);

INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1010,'IL CICLOPE II','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25.6);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1020,'LA PIRAMIDE DEI GHIACCI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,7.12);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1030,'ISOLA DEI PIRATI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1040,'IL GIRO DEL MONDO IN 80 GIORNI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);

INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1050,'IL LOTO BIANCO','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/1970',5010,3010,4010,7);

-------------------------DELETE BEFORE INSERT-----------------------------------
DELETE FROM LIBRO_BKS WHERE ID =1060;
DELETE FROM LIBRO_BKS WHERE ID =1070;
DELETE FROM LIBRO_BKS WHERE ID =1080;
DELETE FROM LIBRO_BKS WHERE ID =1090;
DELETE FROM LIBRO_BKS WHERE ID =1100;
DELETE FROM LIBRO_BKS WHERE ID =1110;
------------------------------INSERT---LIBRO_BKS-------------------------------
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1060,'LA GUERRA DEI MONDI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);

INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1070,'MINORITY REPORT','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25.6);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1080,'OCEAN ELEVEN','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,7.12);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1090,'NOME DELLA ROSA','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1100,'TRE UOMINI A ZONZO','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);

INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1110,'L ULTIMO DEI MOICANI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/1970',5010,3010,4010,7);

-------------------------DELETE BEFORE INSERT-----------------------------------
DELETE FROM LIBRO_BKS WHERE ID =1120;
DELETE FROM LIBRO_BKS WHERE ID =1130;
DELETE FROM LIBRO_BKS WHERE ID =1140;
DELETE FROM LIBRO_BKS WHERE ID =1150;
DELETE FROM LIBRO_BKS WHERE ID =1160;
DELETE FROM LIBRO_BKS WHERE ID =1170;
------------------------------INSERT---LIBRO_BKS-------------------------------
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1120,'DUNE','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1130,'BLAD RUNNER','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25.6);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1140,'I PILASTRI DELLA TERRA','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,7.12);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1150,'ULISSE','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,25);
INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1160,'I  PROMESSI SPOSI','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/2005',5010,3000,4000,9.99);

INSERT INTO LIBRO_BKS (ID,TITOLO,DESCRIZIONE,DATA_PUBLICAZIONE,GENERE_ID,EDITORE_ID,AUTORE_ID,PREZZO)
VALUES (1170,'DIVINA COMMEDIA','UNA SPY STORY AMBIENTATA IN ANTARTIDE.','10/10/1970',5010,3010,4010,7);

----------------------------------DELETE  GENERE BKS------------------------------------------

DELETE FROM GENERE_BKS WHERE ID=5000;
DELETE FROM GENERE_BKS WHERE ID=5010;
DELETE FROM GENERE_BKS WHERE ID=5020;
DELETE FROM GENERE_BKS WHERE ID=5030;
-------------------------------INSERT GENERE_BKS ------------------------------------------------
INSERT INTO GENERE_BKS VALUES(5000,'GIALLI');
INSERT INTO GENERE_BKS VALUES(5010,'AVVENTURA');
INSERT INTO GENERE_BKS VALUES(5020,'ROSA');
INSERT INTO GENERE_BKS VALUES(5030,'STORICI');

------------------------------------DELETE EDITORE_BKS-------------------------------------------------------------------------
DELETE FROM EDITORE_BKS WHERE ID=3000;
DELETE FROM EDITORE_BKS WHERE ID=3010;
--------------------------------------INSERT EDITORE_BKS---------------------------------------------------------------
INSERT INTO EDITORE_BKS VALUES(3000,'FELTRINELLI');
INSERT INTO EDITORE_BKS VALUES(3010,'MONDADORI');
--------------------------------------DELETE AUTORE_BKS------------------------------------------------------------
DELETE FROM AUTORE_BKS WHERE ID=4000;
DELETE FROM AUTORE_BKS WHERE ID=4010;


-------------------------------------------DELETE AUTORE_BKS-------------------------------------------
DELETE FROM AUTORE_BKS WHERE ID=4000;
DELETE FROM AUTORE_BKS WHERE ID=4010;

----------------------------------INSERT AUTORE_BKS-------------------------------------------------------------
INSERT INTO AUTORE_BKS VALUES(4000,'SMITH','WILBUR','SCRITTORE LIBRI AVVENTURA'); 
INSERT INTO AUTORE_BKS VALUES(4010,'BANANA','YOSHIMOTO','SCRITTORE LIBRI ROMANTICI'); 


---------------------------------------------DELETE USER_BKS-------------------------------------------------------
DELETE FROM USERS_BKS WHERE ID=10;
DELETE FROM USERS_BKS WHERE ID=20;
DELETE FROM USERS_BKS WHERE ID=30;

-----------------------------------------------INSERT USERS_BKS----------------------------------------------------
INSERT INTO USERS_BKS(ID,NOME,COGNOME,EMAIL,PASSWORD,PROFILE) VALUES(10,'SUPERADMIN','TAZIO','SUPERADMIN@SPQR.IT','SUPERADMIN',400);
INSERT INTO USERS_BKS(ID,NOME,COGNOME,EMAIL,PASSWORD,PROFILE) VALUES(20,'ADMIN','SEMPRONI','ADMIN@SPQR.IT','ADMIN',300);
INSERT INTO USERS_BKS(ID,NOME,COGNOME,EMAIL,PASSWORD,PROFILE) VALUES(30,'CARTUSER','CAIO','USER@SPQR.IT','CARTUSER',200);


---------------------------------------DELETE USER_PROFILE_BKS---------------------------------------
DELETE FROM USER_PROFILE_BKS WHERE ID=100;
DELETE FROM USER_PROFILE_BKS WHERE  ID=200;
DELETE FROM USER_PROFILE_BKS WHERE ID=300;
DELETE FROM USER_PROFILE_BKS WHERE  ID=400;
-----------------------------INSERT USER_PROFILE_BKS-----------------------------------------------

INSERT INTO USER_PROFILE_BKS(ID,NOME) VALUES(400,'SUPERADMIN');
INSERT INTO USER_PROFILE_BKS(ID,NOME) VALUES(300,'ADMIN');
INSERT INTO USER_PROFILE_BKS(ID,NOME) VALUES(200,'CARTUSER');
INSERT INTO USER_PROFILE_BKS(ID,NOME) VALUES(100,'USER');

---------------------------------------DELETE FUNCTION_BKS-------------------------------------------------------------
DELETE FROM FUNCTION_BKS WHERE ID=10000;
---------------------------------------INSERT INTO FUNCTION_BKS-------------------------------------------------------------
INSERT INTO FUNCTION_BKS(ID,NOME,URL_FUNCTION) VALUES(10000,'RICERCA LIBRI','RICERCALIBRIJSON');
---------------------------------------DELETE PROFILE_FUNCTION_MENU_BKS----------------------------------------------------------

DELETE FROM PROFILE_FUNCTION_MENU_BKS WHERE ID_FUNCTION=10000 AND ID_PROFILE=100;
--------------------------------INSERT PROFILE_FUNCTION_MENU_BKS-------------------------------------
INSERT INTO PROFILE_FUNCTION_MENU_BKS(ID_FUNCTION,ID_PROFILE) VALUES(10000,100);

SELECT PF.ID_PROFILE,P.NOME FROM FUNCTKION_BKS AS F,
PROFILE_FUNCTION_MENU_BKS AS 
PF , USER_PROFILE_BKS AS P  WHERE P.ID=PF.ID_PROFILE AND F.ID=PF.ID_FUNCTION AND F.URL_FUNCTION = 'RICERCALIBRIJSON' ;

SELECT * FROM FUNCTKION_BKS;
SELECT * FROM PROFILE_FUNCTION_MENU_BKS ;




